### ISSUE TITLE
GetPolyData of 3D representation python

### ISSUE THREAD

**Issue by mauigna06** [chir-set/ExtraMarkups#5]
Hi @chir-set

Thank you for your work on this.

I found the tube markup very useful to contour segmentations, could you please make the (tips capped) polydata available from python? Maybe a button to convert the markup to a mrmlModel, then the model could be included on a segmentation object later

Thanks a lot

**Comment by chir-set** [comment]
> (tips capped) polydata available

Do you mean [this](https://github.com/chir-set/SlicerExtraMarkups/blob/main/Shape/MRML/vtkMRMLMarkupsShapeNode.h#L109) function ?



> Maybe a button to convert the markup to a mrmlModel,

It's technically fairly straightforward. It's not implemented on the basis that stock markups nodes do not provide such functionality. For example, the ROI markups node could have provided such a facility : create a tetrahedral model. I assumed that markups nodes do not have such a role. I may still do it, and would appreciate feedback from other developers. @lassoan  @pieper

**Comment by lassoan** [comment]
You can get the mesh via the layout manager -> view -> displayable manager -> widget -> representation, but it is a bit too complicated and only works if the widget is displayed in a view. We should have nicer, cleaner interface. 

One option is to use measurements. Markup nodes can have any number of measurements (https://apidocs.slicer.org/master/classvtkMRMLMeasurement.html). We have added the MeshValue property so that a mesh can be associated with a measurement. We have not yet implemented display of the mesh value and/or export to model node, but that it the plan. We already use this for closed surface area measurement. Search for Get MeshValue/SetMeshValue in Markups module for more details.

Another option would be to compute the mesh in the shape markup node or shape module logic and add add a method that can return the computed mesh.

Before we start relying on this module in other extensions, it is important to fix the module names. The module title can be anything, but the module name should be MarkupsShape and MarkupsLabel. Shape and Label would be very broad, generic, an extension should not reserve such a name. It also not good because it does not make it clear that it extends the Markups module.

**Comment by chir-set** [comment]
> The module title can be anything, but the module name should be MarkupsShape and MarkupsLabel. Shape and Label would be very broad, generic, an extension should not reserve such a name.

I'm afraid to be missing your point here. There are vtkMRMLMarkups{Shape,Label}Node and qMRMLMarkups{Shape,Label}Widget classes with a clear naming hierarchy. Could you please clarify ?

**Comment by lassoan** [comment]
The module, logic, widget class names, folder and file names, etc. should all have "Markups" in them (MarkupsShape instead of just Shape).

**Comment by chir-set** [comment]
Renaming things from '*Shape*' to '*MarkupsShape*' will take a lot and a lot of time.

Renaming MODULE_NAME from 'Shape' to 'MarkupsShape' has side effects. The consequential naming pattern would divert from stock markups nodes. For example, there is 'vtkSlicerROIWidget.h' instead of 'vtkSlicerMarkupsROIWidget.h'. Here there would be 'vtkSlicerMarkupsShapeWidget.h' instead of 'vtkSlicerShapeWidget.h'.

It's a hard step, and a lengthy nightmare above all,

**Comment by lassoan** [comment]
This renaming takes about 20-30 minutes in total (simple search and replace in full text of all files + filenames). I'm OK with doing it, just le me know (I just want to avoid both of us doing the work in parallel).

All this discussion is a proof that you did well! When you submitted the extension I did not want to push you too much on using proper module names because I was not sure how much other extensions will use these modules. However, it seems that the modules are useful and people are interested in using them, so we need to clean up things now, because later it will be much harder.

**Comment by lassoan** [comment]
> The consequential naming pattern would divert from stock markups nodes

We would follow the Markups module's naming convention.

By widget class name I meant the module widget's class name - but I've realized now that this module doesn't have a "module widget" (because there is no module GUI), so there is nothing to do there.

**Comment by chir-set** [comment]
> This renaming takes about 20-30 minutes in total

I could rename things quite quickly using a text editor's 'Find/Replace' facility, while it was quite a problem refractoring in my preferred IDE. Would this [branch](https://github.com/chir-set/SlicerExtraMarkups/tree/Rename) meet your expectancy ?

**Comment by chir-set** [comment]
> I've realized now that this module doesn't have a "module widget" (because there is no module GUI), so there is nothing to do there.

Should we therefore stick to the 'main' branch as it is ? Without merging branch 'Rename' ?

**Comment by chir-set** [comment]
> We have not yet implemented display of the mesh value and/or export to model node, but that it the plan.

I wish to answer @mauigna06 request also : 

> Maybe a button to convert the markup to a mrmlModel

Taking into account : 

> We have not yet implemented display of the mesh value and/or export to model node, but that it the plan

Should I go forward adding a GUI functionality to create a Model from a closed surface in ExtraMarkups ?

**Comment by chir-set** [comment]
Hi @mauigna06,

I think [this](https://github.com/chir-set/Tools7/tree/master/MarkupsToSurface) module should fulfil your expectations. It helps creating a model and a segment from some markup nodes.

**Comment by mauigna06** [comment]
Thank you @chir-set 

I tested it creating this segmentation from a tube (shape markup). And it work almost perfectly except where there are self-intersections:

![Captura desde 2023-04-05 17-11-16](https://user-images.githubusercontent.com/19158307/230199298-2e9a8acd-fe8a-4889-ba40-c6cae88f88bc.png)

**Comment by chir-set** [comment]
@mauigna06 

Thank you for uncovering this unexpected issue. I don't have a solution right now. Detecting polydata intersection on itself and manage it... no clues. The more so that a tube can be a ball of wool too !
